# Generated by Django 5.2.6 on 2025-09-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
