# Generated by Django 5.2.6 on 2025-09-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_distributionplatform_distributionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('afrobeat', 'Afrobeat'), ('amapiano', 'Amapiano'), ('bongo', 'Bongo Flava'), ('dancehall', 'Dancehall'), ('gospel', 'Gospel'), ('hiphop', 'Hip Hop'), ('rumba', 'Rumba'), ('reggae', 'Reggae'), ('soca', 'Soca'), ('traditional', 'Traditional'), ('rnb', 'R&B'), ('pop', 'Pop'), ('rock', 'Rock'), ('jazz', 'Jazz'), ('blues', 'Blues'), ('country', 'Country'), ('electronic', 'Electronic'), ('classical', 'Classical'), ('other', 'Other')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.CharField(blank=True, choices=[('afrobeat', 'Afrobeat'), ('amapiano', 'Amapiano'), ('bongo', 'Bongo Flava'), ('dancehall', 'Dancehall'), ('gospel', 'Gospel'), ('hiphop', 'Hip Hop'), ('rumba', 'Rumba'), ('reggae', 'Reggae'), ('soca', 'Soca'), ('traditional', 'Traditional'), ('rnb', 'R&B'), ('pop', 'Pop'), ('rock', 'Rock'), ('jazz', 'Jazz'), ('blues', 'Blues'), ('country', 'Country'), ('electronic', 'Electronic'), ('classical', 'Classical'), ('other', 'Other')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
