# Generated by Django 5.2.6 on 2025-09-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_album_artist_alter_album_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionrequest',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
