# Generated by Django 5.2.4 on 2025-09-07 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_distributionrequest_total_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['slug'], name='idx_album_slug'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['created_at'], name='idx_album_created_at'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['uploader'], name='idx_album_uploader'),
        ),
        migrations.AddIndex(
            model_name='blogcategory',
            index=models.Index(fields=['slug'], name='idx_blogcategory_slug'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='idx_blogpost_slug'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['created_at'], name='idx_blogpost_created_at'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='idx_comment_user'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_at'], name='idx_comment_created_at'),
        ),
        migrations.AddIndex(
            model_name='distributionplatform',
            index=models.Index(fields=['name'], name='idx_platform_name'),
        ),
        migrations.AddIndex(
            model_name='distributionrequest',
            index=models.Index(fields=['artist'], name='idx_distribution_artist'),
        ),
        migrations.AddIndex(
            model_name='distributionrequest',
            index=models.Index(fields=['requested_at'], name='idx_distribution_requested_at'),
        ),
        migrations.AddIndex(
            model_name='distributionrequest',
            index=models.Index(fields=['status'], name='idx_distribution_status'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='idx_profile_user'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['slug'], name='idx_track_slug'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['created_at'], name='idx_track_created_at'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['uploader'], name='idx_track_uploader'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['downloads'], name='idx_track_downloads'),
        ),
    ]
