# Generated by Django 5.2.4 on 2025-09-07 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_artist_delete_genre_alter_album_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='artist_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_artist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_proof',
            field=models.FileField(blank=True, null=True, upload_to='verifications/'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_email_verified'], name='idx_profile_email_verified'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_artist'], name='idx_profile_is_artist'),
        ),
    ]
