# Generated by Django 5.2.4 on 2025-09-07 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_artist_status_profile_is_artist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('purpose', models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('artist_verification', 'Artist Verification')], max_length=20)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='idx_profile_email_verified',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='idx_profile_is_artist',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='otp_created_at',
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_artist', 'artist_status'], name='idx_profile_artist'),
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user', 'code'], name='idx_otp_user_code'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['created_at'], name='idx_otp_created_at'),
        ),
    ]
