# Generated by Django 5.2.4 on 2025-09-07 23:30

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_otp_remove_profile_idx_profile_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionplatform',
            name='ref_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='MWK', max_length=3)),
                ('mobile', models.CharField(max_length=20)),
                ('operator_ref_id', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('response_data', jsonfield.fields.JSONField(blank=True, help_text='Raw PayChangu API response', null=True)),
                ('user_email', models.EmailField(blank=True, help_text="User's email for notifications", max_length=254, null=True)),
                ('distribution_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='core.distributionrequest')),
            ],
            options={
                'indexes': [models.Index(fields=['charge_id'], name='core_paymen_charge__44cef3_idx'), models.Index(fields=['status'], name='core_paymen_status_04c981_idx')],
            },
        ),
    ]
