# Generated by Django 5.2.4 on 2025-09-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_distributionplatform_ref_id_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover_art',
            field=models.ImageField(default=1, upload_to='track_covers/'),
            preserve_default=False,
        ),
    ]
